name: CI

on:
  push:
    branches-ignore:
      - 'root'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1

        with:
          version: 1.11

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Rename artifact
        run: |
          mv build/libs/client-*.jar build/libs/client.jar

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v2

        with:
          name: JAR
          path: build/libs/client.jar
