name: CI

on:
  push:
    branches:
      - root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.11

      - name: Gradle (Build)
        run: sh gradlew build

      - name: Gradle (Publish)
        run: sh gradlew -Pkotdis.user=${{ secrets.MAVEN_USER }} -Pkotdis.password=${{ secrets.MAVEN_PASSWORD }} publish

      - name: Rename artifact
        run: |
          mv kord-extensions/build/libs/client-*.jar kord-extensions/build/libs/client.jar

      - name: Upload artifact (JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: JAR
          path: kord-extensions/build/libs/client.jar
